accounts/urls.py
from django.urls import path, include
from accounts import views

app_name = 'accounts'

urlpatterns = [
	path('', views.Profile.as_view(), name='profile'),
	path('register/', views.user_register, name='register'),
	# path('verify/', views.VerifyCode, name='verify'),
	path('login/', views.UserLogin.as_view(), name='login'),
	path('logout/', views.UserLogout.as_view(), name='logout'),
	path('password_change/', views.PasswordChange.as_view(), name='password_change'),
	# path('', include('django.contrib.auth.urls')),
]


# urlpatterns = [
#     path('login/', views.LoginView.as_view(), name='login'),
#     path('logout/', views.LogoutView.as_view(), name='logout'),

#     path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
#     path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

#     path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
#     path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
#     path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
#     path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
# ]

blog/urls.py
from django.urls import path
from . import views


app_name = "blog"
urlpatterns = [
    path('', views.ArticleList.as_view(), name="article_list"),
    path('<int:id>/<slug:slug>/',
         views.ArticleDetail.as_view(), name="article_detail"),
    path('category/<slug:slug>/', views.CategoryList.as_view(),
         name="article_by_category"),
    path('category/<slug:slug>/page/<int:page>',
         views.CategoryList.as_view(), name="category"),
    path('author/<slug:username>', views.AuthorList.as_view(), name="author"),
    path('author/<slug:username>/page/<int:page>',
         views.AuthorList.as_view(), name="author"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('', include('core.urls', namespace="core")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('admin/', admin.site.urls),
]
handler404 = 'core.views.handler404'

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.html import format_html
from accounts.manager import UserManager
# Create your models here.


class User(AbstractUser):
	username = None
	email = models.EmailField(max_length=125, unique=True)
	is_author = models.BooleanField('author', default=False,
		help_text='Determines whether this user is allowed to write an article')
	avatar = models.ImageField(upload_to='avatars/', default='avatars/default.jpg', blank=True, null=True)
	team_member = models.BooleanField(default=False, blank=True, null=True)
	objects = UserManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['first_name', 'last_name']

	# backend = 'accounts.authentication.EmailBackend'

	def thumbnail(self):
		if self.avatar:
			return format_html("<img width=40 height=40 style='border-radius: 20px;' src='{}'>".format(self.avatar.url))
		return "nothing"
	thumbnail.short_description = "thumbnail"

accounts/forms.py
from django import forms
from django.core.files.images import get_image_dimensions
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.core.validators import EmailValidator
from accounts.models import User


messages = {
    'required': 'این فیلد اجباری است',
    'invalid': 'لطفا یک ایمیل معتبر وارد کنید',
    'max_length': 'تعداد کاراکترها بیشتر از حد مجاز است'
}


class RegisterForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        label='email',
        validators=[EmailValidator('correct email'), ],
        error_messages=messages,
    )
    password1 = forms.CharField(error_messages=messages, widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))
    password2 = forms.CharField(error_messages=messages, widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))

    def clean_email(self):
        email = self.cleaned_data.get('email')
        is_exists = User.objects.filter(email=email).exists()
        if is_exists:
            raise forms.ValidationError('Already exists.')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError('don\'t match.')
        if len(password2) < 8:
            raise forms.ValidationError('8 chars.')
        return password2


class VerifyForm(forms.Form):
    verifier = forms.IntegerField(error_messages=messages)


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.file = kwargs.pop('file')
        super().__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "avatar", "team_member")
        widgets = {'avatar': forms.FileInput}

    # Validating the size
    def clean_avatar(self):
        if self.file is not None:
            picture = self.cleaned_data.get('avatar')
            if picture is None:
                return picture
            width, height = get_image_dimensions(picture)
            content_type = picture.content_type.split('/')
            # im = Image.open(picture)
            # im = im.size - > picture width, height
            if content_type[0] in settings.CONTENT_TYPES and content_type[1] in settings.VALID_FORMATS:
                if picture.size > settings.MAX_UPLOAD_SIZE:
                    raise forms.ValidationError(
                        'Please keep filesize under 2 MB')
            else:
                raise forms.ValidationError('File type is not supported')

            return picture
        return
        # if width != 200:
        # 	raise forms.ValidationError("The image is %i pixel wide. It's supposed to be 100px" % width)
        # if height != 200:
        # 	raise forms.ValidationError("The image is %i pixel high. It's supposed to be 200px" % height)

        # return picture

accounts/views.py
from random import randint
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, FormView
from django.contrib.auth import views
from django.contrib.auth import login, logout
from django.contrib.messages.views import SuccessMessageMixin as message
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth import authenticate
from django.core.mail import send_mail
from accounts.mixins import AuthenticatedMixin
from accounts.models import User
from accounts.forms import RegisterForm, ProfileForm, VerifyForm


# Dashboard (Profile). for changing some data.(name, lastname and ...)
class Profile(LoginRequiredMixin, message, UpdateView):
	model = User
	template_name = 'accounts/profile.html'
	form_class = ProfileForm
	success_url = reverse_lazy('core:home')
	success_message = 'پروفایل شما با موفقیت اپدیت شد'

	def get_object(self):
		return User.objects.get(pk=self.request.user.pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		file = self.request.FILES.get('avatar')
		kwargs.update({'file': file})
		return kwargs


# Registering user
def user_register(request):
	if request.method == 'POST':
		form = RegisterForm(request.POST or None)
		if form.is_valid():
			# global cd, code
			# cd = form.cleaned_data
			# code = randint(10100, 30100)
			# subject = 'کد تایید' ; msg = f"کد تایید {code} برای {cd['email']} \n تیم برنامه نویسی ورکیفای"
			# send_mail(subject, msg, settings.EMAIL_HOST_USER, (cd['email'],))
			cd = form.cleaned_data
			User.objects.create_user(cd['email'], cd['password1'])
			messages.success(request, 'شما با موفقیت ثبت نام کردید', 'success')
			return redirect('accounts:profile')
	else:
		form = RegisterForm() 
	return render(request, 'accounts/register.html', {'form':form})


# # 2 step authentication with verify code
# def VerifyCode(request):
# 	form = VerifyForm(request.POST or None)
# 	if form.is_valid():
# 		verifier = form.cleaned_data.get('verifier')
# 		if code == verifier:
# 			user = User.objects.create_user(email=cd['email'], password=cd['password1'])
# 			user.save()
# 			login(request, user)
# 			messages.success(request, 'شما با موفقیت ثبت نام کردید')
# 			return redirect('core:home')
# 		else:
# 			messages.error(request, 'کد وارد شده اشتباه است')
# 			return redirect('accounts:verify')
# 	return render(request, 'accounts/verify.html', {'form':form})


# Login user
class UserLogin(AuthenticatedMixin, message, views.LoginView):
	template_name = 'accounts/login.html'
	success_message = 'ورود با موفقیت انجام شد'


# Logouting user
class UserLogout(views.LogoutView):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.info(request, "شما با موفقیت خارج شدید")
        return super().dispatch(request, *args, **kwargs)


# Changing password
class PasswordChange(message, views.PasswordChangeView):
	template_name = 'accounts/password_change_form.html'
	success_url = reverse_lazy('core:home')
	success_message = 'پسسورد شما با موفقیت عوض شد'

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa-IR" dir="rtl">
	<head>
		<title>{% block title %} {% endblock title %} - ورکیفای</title>

		<!-- Meta Tags -->
		<meta
			name="description"
			content="تیم طراحی سایت ورکیفای آماده خدمت به تمامی مشتریان عزیز است! خدمات ما: طراحی سایت، توسعه سایت و گرافیک | برنامه های تحت ویندوز | اپلیکیشن موبایل و ..."
		/>
		<meta
			name="keywords"
			content="طراحی سایت، توسعه سایت، گرافیک، برنامه های تحت ویندوز، اپلیکیشن موبایل"
		/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<meta http-equiv="X-UA-Compatible" content="IE=7" />
		<!-- Links -->
		<link
			rel="shortcut icon"
			href="{% static 'images/favicon.ico' %}"
			type="image/x-icon"
		/>
		<link rel="stylesheet" href="{% static 'styles/css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'styles/css/backend.css' %}" />
	</head>

	<body>
		{% include 'inc/messages.html' %} {% block content %} {% endblock content %}

		<!-- Scripts -->
		<script src="{% static 'script/main.js' %}"></script>
	</body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %} {% load static %} \
{% load widget_tweaks %} {% block title %} ورود {% endblock title %} {% block content %}
<div class="login-bg">
	<div class="login-wrapper">
		<section class="login-card">
			<header class="login-header">
				<h1>ورود به ورکیفای</h1>
				<p>
					عضو نیستید؟
					<a href="{% url 'accounts:register' %}">همین حالا عضو شو!</a>
				</p>
				{% if form.errors %}
				<p class="alert alert-danger">{{form.errors}}</p>
				{% endif %}
			</header>
			<form method="POST" id="login-form" novalidate>
				{% csrf_token %}
				<div id="email-control" class="form-control">
					<label for="email">ایمیل</label>
					{{form.username|attr:"type:email"|attr:"id:email"|attr:"placeholder:name@example.com"|attr:"data-error:لطفا ایمیل خود را وارد کنید"}}
				</div>
				<div id="password-control" class="form-control">
					<label for="password">کلمه عبور</label>
					<div style="position: relative">
						{{form.password|attr:"type:password"|attr:"id:password"|attr:"placeholder:••••••••"|attr:"data-error:لطفا کلمه عبور را وارد کنید"}}
						<button type="button" class="password-icon">
							<svg
								class="eye-off"
								fill="none"
								stroke="currentColor"
								viewBox="0 0 24 24"
								xmlns="http://www.w3.org/2000/svg"
							>
								<path
									stroke-linecap="round"
									stroke-linejoin="round"
									stroke-width="2"
									d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"
								></path>
							</svg>
						</button>
					</div>
				</div>
				<button type="submit" class="btn btn-block btn-primary">ورود</button>
			</form>
			<div class="divider">یا</div>
			<footer>
				<a href="#" id="login-google" class="btn btn-block btn-google">
					ورود با گوگل
					<span class="google-icon"></span>
				</a>
			</footer>
		</section>
	</div>
</div>
{% endblock content %}

accounts/templates/accounts/password_change_form.html
{% extends "base.html" %}

{% block title %}پسسورد{% endblock %}

{% block content %}
  <h1>Change your password</h1>

  <p>Use the form below to change your password.</p>
  <form method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Change"></p>

  </form>
  
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}
پروفایل
{% endblock title %}

{% block content %}
<main class="container">
  <h1>تنظیمات حساب کاربری</h1>
  <div class="d-flex">
    <form method="POST" class="account-settings" style="width: 100%" enctype="multipart/form-data"> {% csrf_token %}
      <div class="form-control">
        <label for="email">ایمیل</label>
        <!-- <input type="email" id="email" placeholder="name@example.com" /> -->
        {{form.email|attr:"type:email"|attr:"id:email"|attr:"placeholder:name@example.com"}}
      </div>
      <div class="form-control">
        <label for="name">نام</label>
        <!-- <input type="text" id="name" placeholder="مثال: مهدی" /> -->
        {{form.first_name|attr:"type:name"|attr:"id:name"|attr:"placeholder:مثال: مهدی"}}

      </div>
      <div class="form-control">
        <label for="surname">نام خانوادگی</label>
        <!-- <input type="text" id="surname" placeholder="مثال: محمدی" /> -->
        {{form.last_name|attr:"type:text"|attr:"id:surname"|attr:"placeholder:مثال: محمدی"}}
      </div>
      <div class="form-control">
        <label for="photo">تصویر پروفایل</label>
        <!-- <input type="file" id="photo" /> -->
        {{form.avatar|attr:"type:file"|attr:"id:photo"}}
      </div>
      <p>
        آیا میخواهید رمز عبور خود را تغییر دهید؟
        <a href="{% url 'accounts:password_change' %}" class="text-primary">تغییر رمز عبور</a>
      </p>
      <div>
        <button type="submit" class="btn btn-primary">بروزرسانی</button>
        <!-- <button class="btn btn-secondary">تنطیم مجدد</button> -->
      </div>
    </form>
    <div class="account-settings__image d-none">
      <img
        src="{% static 'images/illustrations/profile-details.svg' %}"
        alt="Profile Details"
      />
    </div>
  </div>
</main>
<!-- Main Content end -->
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %} {% load static %} {% load widget_tweaks %} 
{% block title %} ثبت نام {% endblock title %} {% block content %}

<body>
	<div class="signup-bg">
		<section class="signup-card">
			<header class="signup-header">
				<h1>ثبت نام در ورکیفای</h1>
				<p>عضو هستید؟ <a href="{% url 'accounts:login' %}">وارد شوید!</a></p>
			</header>
			<form method="POST" id="signup-form" novalidate>
				{% csrf_token %}
				<div id="email-control" class="form-control">
					<label for="email">ایمیل</label>
					{{form.email|attr:"type:email"|attr:"id:email"|attr:"placeholder:name@example.com"|attr:"data-error:لطفا ایمیل خود را وارد کنید"}}
				</div>
				<div class="form-control">
					<label for="password">کلمه عبور</label>
					<div style="position: relative">
						{{form.password1|attr:"type:password"|attr:"id:password"|attr:"placeholder:••••••••"|attr:"data-error:لطفاکلمه عبور را وارد کنید"}}
						<button type="button" class="password-icon">
							<svg
								class="eye-off"
								fill="none"
								stroke="currentColor"
								viewBox="0 0 24 24"
								xmlns="http://www.w3.org/2000/svg"
							>
								<path
									stroke-linecap="round"
									stroke-linejoin="round"
									stroke-width="2"
									d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"
								></path>
							</svg>
						</button>
					</div>
				</div>
				<div class="form-control">
					<label for="confirm-password">تکرار کلمه عبور</label>
					<div style="position: relative">
						{{form.password2|attr:"type:password"|attr:"id:password"|attr:"placeholder:••••••••"|attr:"data-error:لطفاکلمه عبور را وارد کنید"}}
						<button type="button" class="confirm-password-icon">
							<svg
								class="eye-off"
								fill="none"
								stroke="currentColor"
								viewBox="0 0 24 24"
								xmlns="http://www.w3.org/2000/svg"
							>
								<path
									stroke-linecap="round"
									stroke-linejoin="round"
									stroke-width="2"
									d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"
								></path>
							</svg>
						</button>
					</div>
				</div>
				<button type="submit" class="btn btn-block btn-primary">ثبت نام</button>
			</form>
		</section>
	</div>
	{% endblock content %}
</body>

accounts/templates/accounts/verify.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
کد تایید
{% endblock title %}
{% block content %}
<div class="login-bg">
	<section class="login-card" style="height: 57% !important;">
		<form method="POST" id="login-form" novalidate> {% csrf_token %}
			<div class="form-control">
				<label for="active-code">کد فعالسازی</label>
				{{form.verifier}}
			</div>
			<button type="submit" class="btn btn-block btn-primary">
				ثبت نام
			</button>
			<p class="active-text">کد فعالسازی به ایمیل خود را وارد کنید.</p>
		</form>
	</section>
</div>


{% endblock content%}